#!/bin/bash

interval=20
alpha=50

#for K in 1 2 3 4 5 6 7 12 13 16 17 24;
#do
#	cp YinYang.names $K.names
#done

echo "================================="
echo "Generating Predicting Data...(Interval = $interval)"
./format data/X $interval X.range $alpha > X.format
./format Feature $interval Feature.range $alpha > Feature.format

#for K in 1 2 3 4 5 6 7 12 13 16 17 24;
for K in 12;
do
	echo "================================"
	echo "Label: $K"
	echo "Generating Training Data...(Interval = $interval)"

	./convert Feature Label $K $interval $alpha > $K.data

	#awk '{ if ($1 == '$K') { print 1 } else { print -1 } }' Label > temp
	#paste --delimiters=, temp Feature > A.$K
done

#rm -f temp

