#!/bin/bash


#for K in 1 2 3 4 5 6 7 12 13 16 17 24;
for K in 2;
do
	echo "================================="
	echo "Label: $K"

	sed "s/-1/0/g" $K.vote > temp
	sed "s/1/$K/g" temp > $K.cheat

done

