#!/bin/bash

interval=10
alpha=50

echo "================================="
echo "Generating Predicting Data...(Interval = $interval)"
./format data/X $interval X.range $alpha > X.format
./format Feature $interval Feature.range $alpha > Feature.format
#./format FeatureABE $interval FeatureABE.range $alpha > FeatureABE.format
echo "Scaling..."
svm-scale X.format > X.scale
svm-scale Feature.format > Feature.scale
#svm-scale FeatureABE.format > FeatureABE.scale

#for K in 1 2 3 4 5 6 7 12 13 16 17 24;
#for K in 3;
#do
#	echo "================================="
#	echo "Label: $K"
#	echo "Generating Training Data...(Interval = $interval)"
#	./convert Feature Label $K $interval $alpha > $K.train
#	echo "Scaling..."
#	svm-scale $K.train > $K.scale
#done

